### ISSUE TITLE
Pobieranie danych z formularzu za pomocą przycisku i wysyłanie do bazy

### ISSUE THREAD

**Issue by Hayk-Tovmasyan** [zsl-hub/game-team-gcp#21]

**Comment by Mistermakos** [comment]
Dodawanie Pokoju do bazy danych z formularza

**Comment by Mistermakos** [comment]
Na endpoint: "http://loclahost:8080/api/v1/Room/", metodą POST przesłać dane z formularza z tworzenia boarda. 
body: roomName, startingColor.
